# Generated by Django 5.2.4 on 2026-01-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='current_answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
