# Generated by Django 5.2.4 on 2026-01-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_player_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
    ]
