# Generated by Django 5.2.9 on 2026-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
