# Generated by Django 5.2.4 on 2026-02-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gamesession_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
