# Generated by Django 5.2.9 on 2026-02-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_player_channel_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('session', 'name')},
        ),
    ]
