# Generated by Django 5.2.4 on 2026-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='score_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Вибір варіанта'), ('true_false', 'Правда/Брехня'), ('puzzle', 'Пазл (Порядок)'), ('text_input', 'Ввід тексту')], default='multiple_choice', max_length=20),
        ),
    ]
