# Generated by Django 5.2.4 on 2026-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_score_player_streak_playeranswer_score_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
