# Generated by Django 5.2.4 on 2026-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answeroption_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranswer',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
