# Generated by Django 5.2.4 on 2026-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_playeranswer_accuracy_playeranswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='Lucky', max_length=50),
        ),
    ]
