# Generated by Django 5.2.4 on 2026-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='top=shortHair&eyes=default&mouth=default&clothing=shirt', max_length=200),
        ),
    ]
