# Generated by Django 5.2.4 on 2026-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='top=shortFlat&eyes=default&mouth=default&clothing=shirtCrewNeck', max_length=200),
        ),
    ]
